controller_list:
  - name: fake_cart_cnc_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
  - name: fake_cart_tool_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_3
initial:  # Define initial robot poses per group
  - group: cart_cnc
    pose: home